name: release

on: 
  push:
    tags:
      - 'v*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup dotnet 3.0.100
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100' # SDK Version to use.
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    # dotnet restore
    - name: restore
      run: dotnet restore
    # dotnet build and publish
    - name: Build with dotnet
      run: dotnet build --configuration Release
    # dotnet test
    - name: test
      run: dotnet test
    # dotnet create package
    - name: Create the package
      run: dotnet pack --configuration Release
    # publish the package
    - name: Publish the package to GPR
      run: dotnet nuget push src/bin/Release/*.nupkg